name: Laravel Pint
on: [push]
jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: "laravel-pint"
          uses: aglipanci/laravel-pint-action@2.2.0
          with:
            verboseMode: true